# tasks "main"

---

  - name: "Create Azure Virtual Machine"
    azure_rm_virtualmachine:
      admin_username: "{{vm_admin_username}}"
      image:
        offer: "{{vm_image['offer']}}"
        publisher: "{{vm_image['publisher']}}"
        sku: "{{vm_image['sku']}}"
        version: "{{vm_image['version']}}"
      location: "{{vm_location}}"
      name: "{{vm_name}}"
      resource_group: "{{vm_resource_group}}"
      ssh_password_enabled: 'False'
      ssh_public_keys:
        - path: "/home/{{vm_admin_username}}/.ssh/authorized_keys"
          key_data: "{{vm_ssh_pub_key}}"
      started: 'True'
      state: 'present'
      storage_account_name: "{{vm_storage_account_name}}"
      vm_size: "{{vm_param_size}}"
