# tasks "main"

---

  - name: "Check if Elasticsearch installed"
    script: "scripts/tasks/main_first.ps1"
    register: "app_ins_stat"

  - name: "Set Elasticsearch install state message"
    set_fact:
      app_ins_stat_msg: "{{(app_ins_stat['stdout'] == 'True')|ternary('Installed', 'Not Installed')}}"

  - name: "Print Elasticsearch install state message"
    debug:
      msg: "Elasticsearch state: {{app_ins_stat_msg}}"

  - name: "Get version of installed Elasticsearch"
    script: "scripts/tasks/main_second.ps1"
    register: "app_ins_ver"
    when: (app_ins_stat['stdout'] == 'True')

  - name: "Print Elasticsearch version message"
    debug:
      msg: "Elasticsearch version: {{app_ins_ver['stdout']}}"
    when: (app_ins_stat['stdout'] == 'True')

  - name: "Check if Elasticsearch need to uninstall"
    set_fact:
      app_uninstall: "{{((package['version_force'] == 'True') and (package['version'] != app_ins_ver))|
                      ternary ('True', 'False')}}"
    when: (app_ins_stat['stdout'] == 'True')

  - name: "Set Elasticsearch role install task action"
    set_fact:
      app_install: "{{((es_uninstall == 'False') and ((app_ins_stat['stdout'] != 'True') or ((app_ins_stat['stdout'] ==
                    'True') and (app_uninstall|default('False') == True))))|ternary('True', 'False')}}"

  - include: "uninstall.yml"
    when: (es_uninstall == 'True') or
          (app_uninstall|default('False') == True)

  - include: "install.yml"
    when: (app_install == True)

  - include: "tests/uninstall.yml"
    when: (es_uninstall == 'True')

  - include: "tests/install.yml"
    when: (app_install == True)

  - name: "Print Elasticsearch uninstall message"
    debug:
      msg: "Elasticsearch was uninstalled or not initially installed"
    when: (es_uninstall == 'True')

  - name: "Print Elasticsearch install message"
    debug:
      msg: "Elasticsearch was seccesfully installed"
    when: (app_install == True)

  - name: "Print Elasticsearch empty message"
    debug:
      msg: "Nothing to do"
    when: (es_uninstall == 'False') and
          (app_install == False)
